-- USUARIO sys as sysdba
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

-- Usuario 1: ALVARO
CREATE USER ALVARO IDENTIFIED BY "123456";
GRANT CONNECT, DBA TO ALVARO;
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO ALVARO;
GRANT EXECUTE ON SYS.UTL_I18N TO ALVARO;
-- Privilegios personalizados
GRANT CREATE TABLE TO ALVARO;
GRANT CREATE PROCEDURE TO ALVARO;

-- Usuario 2: ANGELG
CREATE USER ANGELG IDENTIFIED BY "123456";
GRANT CONNECT, DBA TO ANGELG;
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO ANGELG;
GRANT EXECUTE ON SYS.UTL_I18N TO ANGELG;
-- Privilegios personalizados
GRANT CREATE VIEW TO ANGELG;
GRANT CREATE TRIGGER TO ANGELG;

-- Usuario 3: FERNANDO
CREATE USER FERNANDO IDENTIFIED BY "123456";
GRANT CONNECT, DBA TO FERNANDO;
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO FERNANDO;
GRANT EXECUTE ON SYS.UTL_I18N TO FERNANDO;
-- Privilegios personalizados
GRANT CREATE SEQUENCE TO FERNANDO;
GRANT UNLIMITED TABLESPACE TO FERNANDO;

-- Usuario 4: ISAI
CREATE USER ISAI IDENTIFIED BY "123456";
GRANT CONNECT, DBA TO ISAI;
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO ISAI;
GRANT EXECUTE ON SYS.UTL_I18N TO ISAI;
-- Privilegios personalizados
GRANT CREATE SYNONYM TO ISAI;
GRANT CREATE MATERIALIZED VIEW TO ISAI;